### ISSUE TITLE
How are contacts modeled in RLBench?

### ISSUE THREAD

**Issue by ericrosenbrown** [stepjam/RLBench#144]
I was wondering how contacts are modeled in RLBench? In order to grasp an object, does RLBench set a fixed kinematic constraint between the gripper and object to maintain contact, or are collision models between the gripper and object simulated when holding the object? Thanks!

**Comment by stepjam** [comment]
Hi.
So this actually depends on the task. Usually, for rigid objects, ‘fake’ grasping is employed: this mean that if a graspable object* is detected within the gripper after a close command, the object will be attached the the arm (therefore, the object will not ‘slip’). However, for articulated objects (e.g. draws, door handles, etc), this does not happen otherwise this would break the articulated joint. If you want to disable fake grasping, you can set it here: https://github.com/stepjam/RLBench/blob/master/rlbench/task_environment.py#L41.

Please reopen if this does not answer your question. 

*graspable objects are marked in individual task files, e.g. https://github.com/stepjam/RLBench/blob/master/rlbench/tasks/pick_and_lift.py#L19
