### ISSUE TITLE
To be compatible with openai gym environment

### ISSUE THREAD

**Issue by KuKuXia** [stepjam/RLBench#20]
Hi, stepjam!
     I really appreciate what you've done and this is a good benchmark for researchers in robotics. But I hope if you can make the tasks be compatible with OpenAI's gym environment since there are a lot of RL algorithms developed by others which we can use as the baseline performance easily. Thanks.

**Comment by stepjam** [comment]
Hi @KuKuXia ,
The tasks have the same methods that Gym Envs have, so what would be the additional benefit of this? The reason why I haven't already done this is that because RLBench is unique in the sense that it has the ability to get demos, so it's not super clear if that would add necessary fluff to the code. I am open to pull requests though :)

**Comment by KuKuXia** [comment]
Hi, stepjam!
Thanks for your replay. I've changed my project to use the IKEA Furniture Assembly Environment. 
Since it's compatible with openai's gym environment and I can mainly focus on the RL algorithms. I'm using openai's baseline as the baseline performance quickly without additional code modification. I hope someone can make a whole working code using this environment and make it public now.

**Comment by stepjam** [comment]
I've had quite a few emails about gym support, so I perhaps I should add in. Expect to see this live some time tomorrow.

**Comment by KuKuXia** [comment]
Hi, stepjam,
Thanks for your great work. I'm looking forward to seeing your new features now. I'll keep watching your repo and wish it will help build my project.

**Comment by stepjam** [comment]
Now merged to main branch. Enjoy!
