### ISSUE TITLE
Render speed penalty

### ISSUE THREAD

**Issue by timtody** [stepjam/RLBench#36]
- Using the gym api

when calling render, I'm getting a penalty of 30x on my step time. Is this to be expected? Are there ways to improve step time while rendering? Like, for example, speeding up simulation time or something?

I'm curious, because I'm currently runinng experiments where I want to inspect the robot at different time steps but I don't know when these appear beforehand. One solution would be recording a video of every time step but given the insane slow down I consider this infeasible. 
As an alternative I thought of recording all actions which would allow me to "replay" certain parts of the simulation. For that to work I would need to be able to restore the simulator state for arbitrary time points. Is this possible and if yes what is the suggested approach for this?

**Comment by stepjam** [comment]
Hi timody,

Yes this penalty is to be expected. There's always going to be a penalty when calling the rendering, and yes, as you point out ideally you should be calling this only when needed. Alas, you have a few options:
- You can decrease the size of the images by modifying [this line](https://github.com/stepjam/RLBench/blob/master/rlbench/gym/rlbench_env.py#L73).
- You can swap to using the `RenderMode.EXTERNAL_WINDOWED` rather than the `RenderMode.EXTERNAL_WINDOWED` [here](https://github.com/stepjam/RLBench/blob/master/rlbench/gym/rlbench_env.py#L75). The former wont have any shadows, and so it will be faster to render.
- Ensure that you are using the GPU to render. Beware, if you use something like Xvfb, then it **does not use hardware rendering**, so this will dramatically slow down your rendering. 
- As you pointed out, you could replay the trajectories later. I actually plan to include support for 'reset to demonstrations' which would allow you to reset to a specific point in the demo. However, it is not supper high on the priority list at the moment. 

Best,
Stephen

**Comment by timtody** [comment]
Hi Stephen,

thanks for the tips! I'm going to try decreasing the image size and switch the render mode, as I don't need shadows for my purposes.
I'm aware of the issue with virtual frame buffers, thank you. Do you know how I can make sure that coppelia sim is using the gpu to render?
About replaying trajectories: what do you mean with demonstrations? If you give me a few pointers I could try making a pull request.

Best
Julius

**Comment by timtody** [comment]
I tried you suggestions: switching the render mode yields a noticeable difference in appearance (no shadows) and improves render time. Yay! Changing the resolutions parameters, however, does not seem to actually change the resolution of the gym cam.

**Comment by superggb** [comment]
hello sir, I have the same problem about the rendering speed, so how can I switch to use GPU to render?

**Comment by stepjam** [comment]
I'm assuming you mean when you run headless? This is related directly to CoppelisSim, and is not currently supported, you can track the issue here: https://github.com/stepjam/PyRep/issues/150

**Comment by stepjam** [comment]
You can now do GPU rendering: https://github.com/stepjam/RLBench/blob/master/README.md#running-headless
