### ISSUE TITLE
Gym doesn't support End Effector-related action mode (EE_POSE)

### ISSUE THREAD

**Issue by bycn** [stepjam/RLBench#50]
Setting action_mode = ActionMode(ArmActionMode.DELTA_EE_POSE) for the gym reach_target task, for example, gives rlbench.task_environment.InvalidActionError: Could not find a path. This is due to the action_space giving out of bounds possibilities. 

Edit: after looking into this it seems that the IK breaks even with tiny epsilon (< 0.0005) movement, perhaps when colliding into an object? not sure.

**Comment by stepjam** [comment]
Yes the deltas need to be small because its using the Jacobians. If you want a larger delta, then you can use ABS_EE_POSE_PLAN or DELTA_EE_POSE_PLAN in V 1.0.6: https://github.com/stepjam/RLBench/blob/1.0.6/rlbench/action_modes.py#L45.

This will be merged into main soon. It uses path planning to get to a target rather than getting the joint angles via the Jacobian.

Please reopen if you have further questions :)

**Comment by bycn** [comment]
Thank you stephen!

**Comment by bycn** [comment]
I can't reopen this issue — but could you tell me what delta for example the panda arm can be set to? I'm still getting errors w/ actions on the order of 0.01
