### ISSUE TITLE
Stepping speeds

### ISSUE THREAD

**Issue by bycn** [stepjam/RLBench#55]
What stepping speeds are you seeing for the base (i.e., delta joint velocity), no cameras? I'm seeing 0.008s flat, but this seems to be too slow for our research. For example, mujocopy sees 0.0024s per step.

**Comment by stepjam** [comment]
I get ~0.0055s per step. You cant really compare against mujoco because it is comparing apples and oranges. Mujoco is a physics engine whereas CoppeliaSim (which is what RLBench is built around) is a robotics toolkit/engine which incorporates physics engines. So you get a lot more from CoppeliaSim than you would mujoco, and so step times are naturally going to be longer. 
By the way, 3 times slower isn't particularly that bad anyway, you could just spawn more environments to increase data throughput.
Best,
Stephen

**Comment by bycn** [comment]
Sounds good Steven, thanks for testing!
