### ISSUE TITLE
dataset generator results?

### ISSUE THREAD

**Issue by bycn** [stepjam/RLBench#67]
https://github.com/stepjam/RLBench/blob/8ff9507a7b6be5b374f6b7e619b4b7eda1f9fd57/tools/dataset_generator.py

Has this been run on the current tasks and uploaded somewhere?

**Comment by stepjam** [comment]
Hi,
No, the plan is to eventually do this, but because the benchmark is still in its 'teething' phase, I figured there would not be much point as there are still changes happening that may invalidate the generated data. Also, the amount of demos people would want would vary; i.e. for RL it way only be 10, but for imitation learning it may be thousands. So for now, I think it's best that people run the script themselves for the tasks they want.
