### ISSUE TITLE
quesionts when run the rlbench.gym

### ISSUE THREAD

**Issue by ChenyangRan** [stepjam/RLBench#75]
Hi, thanks for your project.
I have some questions when using rlbench.gym.

1. The windows always is created and shows the observatioins when env.step() **although I have annotation the env.render()**.
Could you please tell me _**how to stop creating and showing**_ when I using rlbench.gym? I just want to use it in headless mode.
2. Also, I'm using the rlkit to test the rlbench, which **_recommands two envs for exploration and evaluation_**.
But it seems that the rlbench.gym **_cannot launch them in one terminal at the same time_**, could you help me ?
3. Another question is that I **cannot save the logs when running** the rlbench.gym.
The error is :
![image](https://user-images.githubusercontent.com/29306735/85355179-9e7fd900-b53e-11ea-9d15-31db222a535f.png)
I guess the reason is the main process is rlbench.gym, then I launch **_another process_** to save the parameters.
Could you please give me some advice?

Thanks and looking forward your replay.

**Comment by stepjam** [comment]
Hi

1. It sounds like you are using 'human' rendering. If you want headless, then you instead need to call render with mode 'rgb_array', as you would with a standard gym env.

2. I don't know about rlkit specifically, but you need to make sure that `gym.make` (which in turn launches a RLBench/CoppeliaSim instance) is called inside each new process. I imagine rlkit is not doing this.

3. What are you trying to log? If is the parameters of the network then thats a question for rlkit rather than rlbench.

All the best,
Stephen

**Comment by ChenyangRan** [comment]
> Hi
> 
> 1. It sounds like you are using 'human' rendering. If you want headless, then you instead need to call render with mode 'rgb_array', as you would with a standard gym env.
> 2. I don't know about rlkit specifically, but you need to make sure that `gym.make` (which in turn launches a RLBench/CoppeliaSim instance) is called inside each new process. I imagine rlkit is not doing this.
> 3. What are you trying to log? If is the parameters of the network then thats a question for rlkit rather than rlbench.
> 
> All the best,
> Stephen

Thanks, the 3rd question is that the rlkit need to log the parameters of env, and I have solved annotated it and works well.
As for the 2nd question, I just need to launch one env and use this one.
Thanks for your advice!
