### ISSUE TITLE
Questions about the arrangement of waypoint points

### ISSUE THREAD

**Issue by fanSunny** [stepjam/RLBench#88]
When looking at the task demonstration provided by rlbench, I found that the waypoint settings for object grabbing are somewhat different. Some objects have a waypoint set before close_gripper (for example, block grabbing in BlockPyramid). Some objects have no settings, and the robotic arm moves directly to the object grabbing. Take the waypoint.(For example, catch plate in SetTheTable).So what is the rule for setting waypoint?

**Comment by stepjam** [comment]
Hi
That is up to the task designer :) 
When building my tasks, I prefer to place a 'pre-grasp' waypoint above objects before the actual grasp waypoint, but that not always necessary. Hope that helps.

**Comment by ubless607** [comment]
@stepjam Thanks for your amazing work. I have one question about waypoints.
If I want the robot gripper to touch a specific part of the object (e.g., left border of the object), is there any way instead of using the waypoint? Using only the waypoint did not help. I am now refering to this video (https://www.youtube.com/watch?v=bKaK_9O3v7Y).
