### ISSUE TITLE
Changing robotic arm in RLBench

### ISSUE THREAD

**Issue by MarvinChung** [stepjam/RLBench#90]
Hello, thanks for making the great repo.  
I want to change the default arm to the UR3.ttm which is already provided in CoppeliaSim(V-rep).  
Can I just change the codes in environment.py to add the UR3 in SUPPORTED_ROBOTS and add UR3.ttm to the robot_ttms directory? 
I hope there can be more documentations on swapping the robotic arms since I might need adding more arms in the future.

**Comment by telejesus2** [comment]
Hi!

I'm also interested in using the UR3 robot with RLBench. UR3 is already supported by PyRep so I suggest using the model provided there instead of the one from CoppeliaSim.

My issue comes with the gripper. I would like to use a Robotiq_85 gripper, which is not supported by PyRep. Is there anything that I should keep in mind before importing the CoppeliaSim model into PyRep/RLBench? Thanks! And thanks for RLBench.

**Comment by stepjam** [comment]
Hi, sorry for the delay in getting back to you. 
The 'tip' of the arm would need to be oriented to be the same as the Panda arm, and then saved to the robot_ttms directory. I can add the UR3; but bear in mind that many of the tasks will not be achievable given the small workspace of the ur3

**Comment by stepjam** [comment]
UR5 is now in version (branch) 1.1.0. See the examples/swap_arm.py to see how to swap the arm.
Please note that alternative arms have **limited** support; they may not work with all tasks, as all of the tasks have been designed to be completed with the Panda.
There was no point adding in UR3 because the UR3 workspace is so small that (almost) all RLBench tasks are impossible.
